version: '3'
services:
  app:
    build:
      args:
        user: reporteruser
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: reporter-app
    container_name: reporter-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - reporter-network

  nginx:
    image: nginx:latest
    container_name: reporter-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - reporter-network

  mysql:
    image: mysql:8.0
    container_name: reporter-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - reporter-mysql-data:/var/lib/mysql
    networks:
      - reporter-network

networks:
  reporter-network:
    driver: bridge

volumes:
  reporter-mysql-data:
    driver: local 