name: Code Quality Checks

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - '**.php'
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'
      - '**.css'
      - '**.scss'
      - 'composer.json'
      - 'composer.lock'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - '**.php'
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'
      - '**.css'
      - '**.scss'
      - 'composer.json'
      - 'composer.lock'
      - 'package.json'
      - 'package-lock.json'

permissions:
  contents: read

jobs:
  lint:
    name: Code Style & Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install PHP dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm ci

      - name: Run PHP Code Style (Pint)
        run: vendor/bin/pint --test

      - name: Format Frontend
        run: npm run format -- --check

      - name: Lint Frontend
        run: npm run lint

      # - name: Commit Changes
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: fix code style
      #     commit_options: '--no-verify'
