name: Status Check

on:
  workflow_dispatch:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  status-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Environment info
        run: |
          echo "GitHub Actions is running correctly"
          echo "Runner OS: ${{ runner.os }}"
          echo "GitHub Ref: ${{ github.ref }}"
          echo "GitHub Event: ${{ github.event_name }}"
          
      - name: List files
        run: ls -la
        
      - name: PHP version check
        run: php -v || echo "PHP not installed" 